import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import React from "react";
import { AuthShowcase } from "./components/Login";

import { api } from "~/utils/api";
import { NavBar } from "./components/Nav/Nav";
import { WelcomeText } from "./components/WelcomeText/WelcomeText";
import LoginButton from "./components/LoginButton/LoginButton";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "james" });

  return (
    <>
      <Head>
        <title>Note Nomad</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NavBar />
        <div className={styles.container}>
          <WelcomeText />
        </div>
      </main>
    </>
  );
};

export default Home;
